import 'dart:developer' as dev;
import '../../news/models/news_category.dart';
import '../../news/providers/news_pipeline_provider.dart';
import '../models/quiz_question.dart';
import 'firestore_quiz_service.dart';
import 'quiz_cache_service.dart';

class QuizGeneratorService {
  static const _tag = 'Briefed/QuizGen';

  /// Returns 5 quiz questions for [category] (null = daily mix).
  /// L1: local SharedPreferences cache → L2: Firestore (Cloud Function pre-generated).
  /// Returns empty if no complete (5-question) quiz is available yet.
  static Future<List<QuizQuestion>> generate(
    PipelineState pipeline, {
    bool forceRefresh = false,
    NewsCategory? category,
  }) async {
    final cacheCategory = category ?? NewsCategory.world;

    if (!forceRefresh) {
      // L1: local SharedPreferences cache (instant, same-day)
      final cached = await QuizCacheService.load(cacheCategory);
      if (cached != null && cached.length >= 5) {
        dev.log('L1 cache: ${cached.length} Qs for ${cacheCategory.name}',
            name: _tag);
        return cached;
      }
    }

    // L2: Firestore server cache — pre-generated by Cloud Function every 4h,
    // shared across all users so no per-user AI calls are needed.
    final serverQuestions = await FirestoreQuizService.fetchQuestions(category);
    if (serverQuestions != null && serverQuestions.length >= 5) {
      dev.log('L2 Firestore: ${serverQuestions.length} Qs for ${cacheCategory.name}',
          name: _tag);
      await QuizCacheService.save(cacheCategory, serverQuestions);
      return serverQuestions;
    }

    // Quiz not ready yet — Cloud Function generates them every 4h.
    dev.log('No complete quiz available for ${cacheCategory.name} — try again soon',
        name: _tag);
    return [];
  }
}
